### ISSUE TITLE
Full screen Icon repeated

### ISSUE THREAD

**Issue by feguensp** [arnowelzel/photoswipe-fullscreen#2]
Every time a new picture is selected to launch photoswipe light box a new Full screen button is added.
![Screenshot 2022-10-04 220158](https://user-images.githubusercontent.com/96083216/193963444-a216d936-a4d9-4883-879a-55da0e7dc36b.jpg)

**Comment by arnowelzel** [comment]
Do you have an URL for demonstration? What do you mean with "Every time a new picture is selected to launch photoswipe"?

I don't understand the problem and can not reproduce it. See my working example here: https://arnowelzel.de/samples/photoswipe5/

And furthermore the use as part of my WordPress plugin: https://wordpress-demo.arnowelzel.de/lightbox-with-photoswipe-5-overlay-caption/

**Comment by arnowelzel** [comment]
The problem:

`uiRegister` is not only called once but when opening an image again it will be called multiple times. However that callback is not expected to be called more than once when the lightbox opens.

**Comment by feguensp** [comment]
When you click on the first picture than you close it, then you click any other picture, a new full screen icon is displayed. So you get two icons to toggle full screen. 
![Screenshot 2022-10-04 234620](https://user-images.githubusercontent.com/96083216/193977227-beacd273-8435-4b80-a39d-c546e56271a0.jpg)

**Comment by arnowelzel** [comment]
Yes, I know! However I can not fix it!

The problem is, that Photoswipe calls `uiRegister` multiple times!

**Comment by arnowelzel** [comment]
I added a workaround to only add the UI element if it is not added already. It seems, Photoswipe calls `init` and `uiRegister` multiple times after it was opened once.

**Comment by arnowelzel** [comment]
Closed with https://github.com/arnowelzel/photoswipe-fullscreen/commit/3a5c1532947ad4f97066e7cbf82174ae60359905
