### ISSUE TITLE
How to switch off this plugin?

### ISSUE THREAD

**Issue by acwolff** [arnowelzel/photoswipe-fullscreen#6]
I tried to use your plug-in with this extra condition:
If a variable showFsButton is false, no FS button should be shown and the FS mode should not be entered.

I tried this:

    lightbox.on('afterInit', () => {    	
        const fullscreenAPI= fullscreenPlugin.getFullscreenAPI(); 
        if (!showFsButton) {
          fullscreenAPI.exit();
        }

but this gives an error.

Next code does no work either:

    var fullscreenPlugin = new PhotoSwipeFullscreen(lightbox, {
      fullscreenTitle: 'Toggle fullscreen'
    }); 

    lightbox.on('afterInit', () => {    	
        if (!showFsButton) {
          fullscreenPlugin= false
        }

What code should be used to implement this condition?

**Comment by arnowelzel** [comment]
By creating the plugin with passing the lightbox instance, it is enabled and you can not disable it afterwards. It also makes no sense to create the plugin if you don't want to use it anyway.

So one approach is this:

```
lightbox.on('afterInit', () => {    	
    if (showFsButton) {
          const fullscreenPlugin = new PhotoSwipeFullscreen(lightbox, { fullscreenTitle: 'Toggle fullscreen' });
    }
```

Also see https://github.com/arnowelzel/lightbox-photoswipe/blob/5.5.1/assets/ps5/frontend.js#L398-L403 - there it is handled in the same way (also with other plugins which are only created if needed).

**Comment by acwolff** [comment]
Thanks for your answer.
My variable showFsButton is a dynamic variable which can be changed after the opening of the album, but before opening the lightbox, so this solution will not work correctly in my case.
I found the  following solution:

       if (!showFsButton) document.getElementsByClassName("pswp__button--fullscreen-button")[0].remove();

**Comment by arnowelzel** [comment]
Your solution will only hide the button. But one you can still press the [F] key to open the full screen view. If you don't want to have fullscreen for individual images in the collection, this would need additional code in the plugin and an addition image specific "fullScreen" option.
