### ISSUE TITLE
How to Trigger native fullscreen when lightbox opens

### ISSUE THREAD

**Issue by acwolff** [arnowelzel/photoswipe-fullscreen#7]
With this plugin the lightbox is not opened in full screen mode. You have always to click the FS button to get the FS mode.
I like to open the lightbox in FS as is possible withe the PhotoSwipe example https://photoswipe.com/native-fullscreen-on-open/

I tried this code:

 lightbox.on('afterInit', () => {  
      document.getElementsByClassName("pswp__button--fullscreen-button")[0].click(); 

but this does not work correctly.

Which code should mI use to get this done?

**Comment by arnowelzel** [comment]
The idea of the plugin is not to open the lightbox in fullscreen mode but to provide the "fullscreen" button as it existed in PhotoSwipe 4.

So there is no solution for your request with my plugin, sorry. You have to keep using the code you have linked to. Also keep in mind that opening stuff in fullscreen mode without asking the user first, or at least telling them, that images will open full screen, can be quite confusing (that's also the reason why browsers only allow fullscreen as a result of a user interaction like keyboard events, mouse clicks or touchscreen events).

**Comment by acwolff** [comment]
Well even with your plugin it is possible with this code:

 lightbox.on('afterInit', () => {  
       if (showFsButton) {
          document.getElementsByClassName("pswp__button--fullscreen-button")[0].click(); 
          setTimeout(function() {
            pswp.updateSize(true); 
          }, 900);  
        } else {
          document.getElementsByClassName("pswp__button--fullscreen-button")[0].remove();
        }
see this album: https://andrewolff.jalbum.net/Test_PS/

But I have to admit it is a rather clumsy solution.

**Comment by arnowelzel** [comment]
https://andrewolff.jalbum.net/Test_PS/ is very confusing - when I open an image from the gallery I will get to the image full screen and when I close the full screen view by pressing [Esc] the lightbox won't close but I will just return to the non-fullscreen view. Yes, one can always click the "X" symbol to close it, but it would be better when leaving the full screen view would also close the lightbox when it was automatically opened with fullscreen view in the first place.

**Comment by acwolff** [comment]
If you don’t want the full screen mode, you can switch it off in the viewer settings window:
![IMG_1614](https://github.com/user-attachments/assets/93b528ee-f3bb-4a9b-979c-7954acf47db8)

**Comment by arnowelzel** [comment]
That does not work here - eventhough the setting is "no", images still open full screen.

**Comment by acwolff** [comment]
> That does not work here - eventhough the setting is "no", images still open full screen.

Sorry. of course this does not work, because I was testing your FS module!

Album https://andrewolff.jalbum.net/Test-PS/ is now again made with my FS implementation and there it works.

BTW if I open in Windows a page in FS mode via the F11 button, the FS mode returns to normal mode i you click the Esc button,

**Comment by arnowelzel** [comment]
This issue still remains: when an image is opened with automatic fullscreen enabled, pressing the [Esc] key will only leave full screen but the image will still be opened in the lightbox. So at least there should be additional code which handles the event when fullscreen is left again to close the lightbox in case it was opened with automatic fullscreen.

**Comment by acwolff** [comment]
In my opinion it is  ok if the Esc button changes the FS mode into the normal mode, because that happens with any webpage in FS mode on a Windows system.
So I will not change that.

**Comment by arnowelzel** [comment]
The issue is, that FS mode was not manually triggered by the user. So it is like this:

1. a user clicks an image, it will open full screen.
2. the user presses [Esc] since the browser tells him that he can do so to leave the full screen display.
3. the image still displays, but not in full screen view. Pressing [Esc] again will do nothing.

In my opinion this is a very bad UI. When something opens fullscreen on its own it should always close agani when you leave the fullscreen view - no matter if you just press [Esc] or click the "X" symbol.
